### ISSUE TITLE
Possibility to use 3rd party (non-conforming) DI container

### ISSUE THREAD

**Issue by nhaberl** [FastEndpoints/Library#218]
Hi, I have integrated SimpleInjector into my project and would like to know if fastendpoints is capable of using that instead of buit in container ?

**Comment by dj-nitehawk** [comment]
any third party IOC library compatible with the asp.net middleware pipeline could theoretically be used.
there seems to be some specific way to configure simpleinjector with asp.net according to this: https://docs.simpleinjector.org/en/latest/aspnetintegration.html
give it a shot and post your config here for future readers benefit.

however, also found this gh issue https://github.com/dotnet/aspnetcore/issues/41863 where there seems to be some trouble getting simpleinjector to play nice with the new minimal apis which fastendpoints is built around.

**Comment by dotnetjunkie** [comment]
Would it be possible for FastEndpoints to add an interception point that allows overriding the creation/resolving of endpoints (which seem to be the root components in FastEndpoints)? This would typically mean introducing something like an `IEndpointFactory` class, which in the default implementation forwards the call to MS.DI. For instance:

``` c#
// Interception point
public interface IEndpointFactory
{
    object Create(Type endpointType);
}

//  Default implementation (register as scoped)
public sealed record DefaultEndpointFactory(IServiceProvider Container) : IEndpointFactory
{
    public object Create(Type endpointType) => Container.GetRequiredService(endpointType);
}

// Registration
services.AddScoped<IEndpointFactory, DefaultEndpointFactory>();
```

This allows several integration scenarios such as integration of non-conforming containers (e.g. Simple Injector). For instance, a Simple Injector user could in this case integrate using the following code:

``` c#
// Custom implementation
public sealed record SimpleInjectorEndpointFactory(Container Container) : IEndpointFactory
{
    public object Create(Type endpointType) => Container.GetInstance(endpointType);
}

// Overriding the framework provided implementation
services.AddSingleton<IEndpointFactory>(new SimpleInjectorEndpointFactory(container));
```

Please note that the suggested definition of the `IEndpointFactory` interception point is a guess; I'm unsure whether  this abstraction has the proper signature for both FastEndpoints ánd external parties. It might be useful, for instance, to add extra parameters to the `Create` method, such as an `EndpointContext` of some sort. Although this might not be needed for Simple Injector to work, it could certainly allow other integration scenarios to work.

HTH

**Comment by dj-nitehawk** [comment]
the endpoint factory can certainly be done but... the larger issue at hand is that the `HttpContext.RequestServices` is currently referenced from 47 places in the code base.
![screen-record-1662621533](https://user-images.githubusercontent.com/7043768/189059877-b87eae16-ca5f-4a0c-8836-5c5e21c8abe1.png)
so the library won't actually work as expected in some areas.
if somebody can do a PR without breaking the current API, i'd be glad to consider it.

**Comment by dotnetjunkie** [comment]
It shouldn't be a problem that FastEndpoints depends on the MS.DI abstraction for its working. When it comes to loading library abstractions, it's okay for users to configure this in the .NET Core built-in configuration system, which FastEndpoints integrates with.

If, however, there are more places where FastEndpoints tightly couples with the built-in configuration system to resolve end points, this should certainly be something that must be changed in multiple places in order to achieve this new interception point. But I would say that, in case FastEndpoints code is well-structured, there should only be a handful of places that should be changed in order to introduce this new seam -again- it's not a goal to completely replace the coupling with the built-in DI configuration system; just add the ability to intercept how endpoints are created.

Unfortunately, it's hard for me to see which calls need to be abstracted and which are not. I unfortunately also don't have the time to build a PR.

**Comment by dj-nitehawk** [comment]
will investigate more when i get some free time...
thanks for your input :-)

**Comment by dotnetjunkie** [comment]
I created PR #243 for this.

**Comment by dj-nitehawk** [comment]
@dotnetjunkie thank you for your contribution :-)

**Comment by dotnetjunkie** [comment]
You're welcome
